plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Belajar Sequelize Validation dan Helpers
baseurl: "education-intermediate-sequelize-validations-helpers"
url: ""
